version: '2'
services:
    gateway-mariadb:
        extends:
            file: mariadb.yml
            service: gateway-mariadb
    gateway-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: gateway-elasticsearch
    kafka:
        extends:
            file: kafka.yml
            service: kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
